//------------------------------------------------------------------------
// Copyright(c) 2025 Sounds Magic.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"SoundsMagic.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"SoundsMagic VST3 (64Bit)"
#else
#define stringFileDescription	"SoundsMagic VST3"
#endif
#define stringCompanyName		"SoundsMagic\0"
#define stringLegalCopyright	"Copyright(c) 2025 SoundsMagic."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
