//------------------------------------------------------------------------
// Copyright(c) 2025 Senior Project.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"SeniorProject.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"SeniorProject VST3 (64Bit)"
#else
#define stringFileDescription	"SeniorProject VST3"
#endif
#define stringCompanyName		"Senior Project\0"
#define stringLegalCopyright	"Copyright(c) 2025 Senior Project."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
