name: Build
on:
  push:
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Compile
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: .
          build-dir: build
          generator: Visual Studio 17 2022
          options: |
            SMTG_CREATE_PLUGIN_LINK=0
